### ISSUE TITLE
publish a NuGet package

### ISSUE THREAD

**Issue by sparkist97** [vb2ae/OpenWeatherMap.Standard#17]
I think it should be published as a NuGet package so potential users can use easily

**Comment by vb2ae** [comment]
If you create a pull request with change I will push the updated NuGet package

**Comment by sparkist97** [comment]
great, I have already started working on it

**Comment by sparkist97** [comment]
@vb2ae you might want to check the [PR](https://github.com/vb2ae/OpenWeatherMap.Standard/pull/18)
