### ISSUE TITLE
Flag WeatherData and dependent objects with SerializableAttribute

### ISSUE THREAD

**Issue by StuffOfInterest** [vb2ae/OpenWeatherMap.Standard#22]
Testing out this library on a ASP.NET Core 3.1 application.  To avoid repeat calls I'm storing the `WeatherData` object in a memory cache.  This is working fine.  As a next step I'm planning to store the data in a distributed cache (using the `IDistributedCache` interface).  This requires serializing into a byte array before storing.

The `WeatherData` class and any classes referenced from it needs to be decorated with the `[Serializable]` attribute.  This will allow passing the class off to a `BinaryFormatter` for serialization.

Serialization and deserialization could probably be accomplished with a JSON serializer but I believe it will be more efficient to stick with binary serialization if possible.

**Comment by StuffOfInterest** [comment]
Thanks for doing the update!

**Comment by vb2ae** [comment]
your welcome
