### ISSUE TITLE
Add Multilingual support

### ISSUE THREAD

**Issue by vb2ae** [vb2ae/OpenWeatherMap.Standard#4]
Add Multilingual support

**Comment by ForceFK** [comment]
New multilingual are supported, do you have plans to include them in the enum?
https://openweathermap.org/current#multi

**Comment by vb2ae** [comment]
Yes I will

**Comment by mvietri** [comment]
Hi!. I've implemented multilingual support back in 2019 with this PR https://github.com/vb2ae/OpenWeatherMap.Standard/pull/21 

I've read the current OWM documentation and nothing seems to be changed and I think the current implementation merged in that PR is still working.

**Comment by mvietri** [comment]
I am sorry. I misread your comment @ForceFK . I didn't notice that new languages were added by OMW. Please, @vb2ae let me know if you want me to add them!. Cheers.

**Comment by vb2ae** [comment]
@mvietri I will assign the ticket to you.  thanks
